### PR TITLE
00.11 Create container for site content for all pages

### PR DESCRIPTION
**Pull request by AlexeyKasaev3**
Create common template for all pages at App.jsx
Снимок экрана от 2020-01-24 17-52-28

### CODE REVIEW

**Comment by AlexeyKasaev3** [comment]
mt-4 for top will move <main> under fixed <header> and will require additional unnecessary padding-top for <main> or its children elements. mb-4 doesn't mean anything, if you want less than mb-8 it's better to remove mb at all

**Comment by alex-boklag** [comment]
> mt-4 for top will move `<main>` under fixed `<header>` and will require additional unnecessary padding-top for `<main>` or its children elements. mb-4 doesn't mean anything, if you want less than mb-8 it's better to remove mb at all

I suggest to resolve it on lesson today.

**Comment by maksv21** [comment]
Good work👍

**Comment by pbalti** [comment]
I suggest returning back fixed card height for full-screen mode (xl:h-56). 
I just shortened news titles in JSON DB and there is no longer need to have it flexible.

Screenshot_3

**Comment by protonaby** [comment]
I suggest returning back fixed card height for full-screen mode (xl:h-56).
I just shortened news titles in JSON DB and there is no longer need to have it flexible.

Screenshot_3

**Pull request merged**
