### PR TITLE
added supplies page tab

### PR DESCRIPTION
**Pull request by TopVV**
Added required supplies table component for the "Help" page

### CODE REVIEW

**Comment by protonaby** [comment]
Could you please attach screenshot?

**Comment by TopVV** [comment]
> In my opinion, if the file has a jsx markup, it's better to indicate the extension of this file as "**.jsx**"
> 
> [optional] Maybe you shouldn’t take the table header into a separate component, but use the header layout directly in the table component.

done

**Comment by TopVV** [comment]
> Could you please attach screenshot?

this will be displayed as part of the help page (one of the tabs)
some text and buttons will be added by Ivan later on

table

**Comment by TopVV** [comment]
Corrected column "Amount" width (so the word "Кол-во" don't break into two rows on displays < 1400px width)

**Pull request merged**
