### PR TITLE
02.05 Add pop up window with contacts

### PR DESCRIPTION
**Pull request by alex-boklag**
image

### CODE REVIEW

**Comment by protonaby** [comment]
> I think the middle name and last name are not needed here. And maybe write not just contacts, but something like "Contact me"?

As another option we could extend the text to something like "Чтобы приютить питомца, пожалуйста, свяжитесь с координатором Ольгой одним из способов:"

**Comment by alex-boklag** [comment]
> I think it's worth adding an icon for a phone with a link "tel:"

Done!

**Comment by alex-boklag** [comment]
> I think the middle name and last name are not needed here. And maybe write not just contacts, but something like "Contact me"?

Done!

**Comment by alex-boklag** [comment]
> > I think the middle name and last name are not needed here. And maybe write not just contacts, but something like "Contact me"?
> 
> As another option we could extend the text to something like "Чтобы приютить питомца, пожалуйста, свяжитесь с координатором Ольгой одним из способов:"

Done!

**Pull request merged**
