### PR TITLE
00.18 mobile header

### PR DESCRIPTION
**Pull request by maksv21**
It makes header design responsive 

Now the menu opens after clicking on any place in the header, maybe catch only clicking on the logo?

<details>
<summary>Screenshots (traffic)</summary>
Desktop remained as it was

image

pnone
image

phone rotated
image

tablet
image

footer margin
image

One news on phone
image

On the desktop, as it was, nothing broke)
image
</details>

### CODE REVIEW

**Comment by yevhverb** [comment]
Why so many conflicts?

**Comment by maksv21** [comment]
> Why so many conflicts?

edited z-index
right-for-life_front/src/components/AnimalCard/AnimalCard.jsx
right-for-life_front/src/components/ArticleItem/ArticleItem.jsx
right-for-life_front/src/containers/NewsPage/NewsPage.jsx

removed animation library
right-for-life_front/src/containers/AnimalDetailsPage/index.jsx


I'm resolving conflicts, few moments and they won't not be

**Comment by maksv21** [comment]
Sorry to take your time without doing it right away

**Comment by yevhverb** [comment]
image

**Pull request merged**
